###
POST localhost:8080/category
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjg4OTMxMDU3LCJleHAiOjE2ODkwMTc0NTd9.NtePtJ5hL92MXwauhk8EjTmw9Gk57p_8SeoinZva2zE
Content-Type: application/json

{
  "category": "The best"
}

###
PUT localhost:8080/category
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbGJlcnRmZ0…xNjZ9.9mYv2lhGZepPEM_FDIafUmSlomZz7CRCFDbk9IeQ7CE
Content-Type: application/json

{
  "id": 6,
  "category": "NOOOOOOOOO"
}

###
GET localhost:8080/category/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjg4OTMxNzc4LCJleHAiOjE2ODkwMTgxNzh9.qu9C_WFT4JwhnUDRLiC99cIzROnP68pvsxb0yuLBZ2A

###
DELETE localhost:8080/category?idCategory=5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb29nIiwiaWF0IjoxNjg4ODk1NzIwLCJleHAiOjE2ODg5ODIxMjB9.yrP2BGuilKuDV8y8fNDdaMRWd6lzKXT8kq_dTUdvQcQ


