
###
POST localhost:8080/customers
Content-Type: application/json

{
  "name": "Valera",
  "login": "log",
  "password": "password",
  "email": "oleg@oleg.com"
}

###
GET localhost:8080/customers/3
###
GET localhost:8080/customers/email?email=uuu
###
DELETE localhost:8080/customers/2

###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Пол дома",
  "price": 500000,
  "amount": 3
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 1,
  "name": "Лосось",
  "price": 500000,
  "amount": 2
}

###
DELETE localhost:8080/products/3

###
GET localhost:8080/products/3

###
GET localhost:8080/products

###
POST localhost:8080/carts/3
Content-Type: application/json

{
  "id": 3,
  "amount": 1
}

###
GET localhost:8080/customers/3

###
PUT localhost:8080/carts/3/product/3
Content-Type: application/json

{
  "amount": 1
}

###
DELETE localhost:8080/carts/3/products/3

###
POST localhost:8080/promocode
Content-Type: application/json

{
  "promocode": "sale20",
  "percent": 20
}

###
GET localhost:8080/promocode/sale20

###
PUT localhost:8080/promocode/sale15
Content-Type: application/json

{
  "percent": 15
}

###
POST localhost:8080/payment
Content-Type: application/json

{
  "numberCart": "1111",
  "idUser": 3,
  "promoCode": "sale20"

}


